
# Local Management Interface
management-url: "https://173.193.85.173:30442"
admin-username: "admin"
admin-password: "admin"
admin-password-old: "admin"


web-code: 2889-D57C-0FEB-223A-D801-6177-68A9-069A
aac-code: 4444-F462-E174-AA1E-E87B-9F06-E6AC-DA0B
fed-code: 9A08-84CC-599A-5CC2-C4D9-ACD3-AD70-B4D6

db-cert: "./db.pem"
rt-cert: "./runtime.p12"
rt-cert-passwd: "passw0rd"
rt-cert-label: "runtime"

junction-root-page: "./index.html"

definition:  '{ "tcmBehavior": "NEVER_PROMPT", "enableMultipleRefreshTokensForFaultTolerance": true, "description": "An API protection definition configured for OpenBanking", "oidc": { "poc": "https://173.193.85.173:30443/isam", "iss": "https://isam-ob-k8s.com", "lifetime": 20, "cert": "runtime", "enc": { "enc": null, "alg": null, "enabled": false }, "alg": "RS256", "enabled": true, "db": "rt_profile_keys", "dynamicClients":true, "issueSecret":true }, "refreshTokenLength": 40, "grantTypes": [ "RESOURCE_OWNER_PASSWORD_CREDENTIALS", "JWT_BEARER", "IMPLICIT_GRANT", "CLIENT_CREDENTIALS", "AUTHORIZATION_CODE" ], "name": "OpenBanking", "issueRefreshToken":true }'
client: '{ "redirectUri": ["https://static.com", "https://staticclient.com/auth", "https://staticclient.com/auth", "https://localhost:19880/auth"] , "otherInfo": null, "clientId": "static_client", "companyName": "LMFwallet", "contactPerson": "lmf", "jwksUri": null, "contactType": "TECHNICAL", "encryptionCert": null, "companyUrl": "https://lmfwallet.com", "encryptionDb": null, "phone": null, "name": "A oauth client", "requirePkce": false, "definition": "1", "clientSecret": "hunter2", "id": "1", "email": "lfarrell@au1.ibm.com" }' 

jwt-validate-chain-template: '[{"id":"default-jwt", "mode":"validate", "prefix": "0"},  {"id":"default-stsuu", "mode":"issue", "prefix": "1"}]'
jwt-validate-properties: '[{"name":"0.encryption.alg","value":[""]},{"name":"0.encryption.enc","value":[""]},{"name":"0.encryption.symmetricKey","value":[""]},{"name":"0.encryption.db","value":[""]},{"name":"0.encryption.cert","value":[""]},{"name":"0.signing.alg","value":[""]},{"name":"0.signing.symmetricKey","value":[""]},{"name":"0.signing.db","value":[""]},{"name":"0.signing.cert","value":[""]},{"name":"0.signing.jwksUri","value":[""]},{"name":"0.iss","value":[""]},{"name":"0.aud","value":[""]},{"name":"0.sub","value":[""]},{"name":"0.validateExp","value":["false"]},{"name":"0.validateNbf","value":["false"]},{"name":"0.validateSkew","value":["0"]}]'

trace-spec: 'com.tivoli.am.fim.oauth20.*=ALL:com.tivoli.am.fim.trustserver.sts.modules.*=ALL:com.tivoli.am.fim.trustserver.sts.utilities.*=ALL'


ldap-server: 'openldap'
db-server: 'postgresql'
rt-server: 'isamruntime'
